theme: jekyll-theme-minimal
title: Utkarsh's piece of mind
description: Find my resume and interesting blogs here.
plugins:
  - jekyll-feed
highlighter: rouge
markdown: kramdown
defaults:
  - scope:
      path: "_posts"
      type: "posts"
    values:
      layout: post
